# Generated by Django 5.1.5 on 2025-02-21 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('turno', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1, verbose_name='Turno:')),
                ('conferente', models.CharField(max_length=50, verbose_name='Conferente:')),
                ('cliente', models.CharField(max_length=100, verbose_name='Cliente:')),
                ('transportadora', models.CharField(max_length=100, verbose_name='Transportadora:')),
                ('num_nota', models.CharField(max_length=11, verbose_name='Número da nota:')),
                ('quantidade_cx', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4000)], verbose_name='Quantidade de caixas na nota:')),
                ('quantidade_recebidas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4000)], verbose_name='Quantidade de caixas recebidas:')),
                ('motivo', models.CharField(choices=[('Avaria', 'Avaria'), ('Inversão', 'Inversão'), ('Sem Pedido', 'Sem Pedido'), ('Sem Espaço', 'Sem Espaço')], default='Avaria', max_length=11, verbose_name='Motivo da devolução:')),
                ('setor', models.CharField(choices=[('Logística', 'Logística'), ('Comercial', 'Comercial'), ('Fábrica', 'Fábrica'), ('Cliente', 'Cliente')], default='Logística', max_length=9, verbose_name='Setor que causou a devolução:')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da devolução:')),
            ],
        ),
    ]
