# Generated by Django 5.1.5 on 2025-02-09 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariomodel',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='formulariomodel',
            name='cliente',
            field=models.CharField(max_length=100, verbose_name='Cliente:'),
        ),
        migrations.AlterField(
            model_name='formulariomodel',
            name='conferente',
            field=models.CharField(max_length=50, verbose_name='Conferente:'),
        ),
        migrations.AlterField(
            model_name='formulariomodel',
            name='motivo',
            field=models.CharField(choices=[('Avaria', 'Avaria'), ('Inversão', 'Inversão'), ('Sem Pedido', 'Sem Pedido'), ('Sem Espaço', 'Sem Espaço')], default='Avaria', max_length=11, verbose_name='Motivo da devolução:'),
        ),
        migrations.AlterField(
            model_name='formulariomodel',
            name='num_nota',
            field=models.CharField(max_length=11, verbose_name='Número da nota:'),
        ),
        migrations.AlterField(
            model_name='formulariomodel',
            name='quantidade_cx',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4000)], verbose_name='Quantidade de caixas na nota:'),
        ),
        migrations.AlterField(
            model_name='formulariomodel',
            name='quantidade_recebidas',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4000)], verbose_name='Quantidade de caixas recebidas:'),
        ),
        migrations.AlterField(
            model_name='formulariomodel',
            name='setor',
            field=models.CharField(choices=[('Logística', 'Logística'), ('Comercial', 'Comercial'), ('Fábrica', 'Fábrica'), ('Cliente', 'Cliente')], default='Logística', max_length=9, verbose_name='Setor que causou a devolução:'),
        ),
        migrations.AlterField(
            model_name='formulariomodel',
            name='transportadora',
            field=models.CharField(max_length=100, verbose_name='Transportadora:'),
        ),
        migrations.AlterField(
            model_name='formulariomodel',
            name='turno',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1, verbose_name='Turno:'),
        ),
        migrations.AlterField(
            model_name='formulariomodel',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da devolução:'),
        ),
    ]
